export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-MapleAI-Cache",
  cacheHit: "X-MapleAI-Cache-Hit",
  costSaved: "X-MapleAI-Cost-Saved",
  fallbackAttempts: "X-MapleAI-Fallback-Attempts",
  latencyMs: "X-MapleAI-Latency-Ms",
  model: "X-MapleAI-Model",
  progress: "X-MapleAI-Progress",
  provider: "X-MapleAI-Provider",
  requestId: "X-MapleAI-Request-Id",
  responseCost: "X-MapleAI-Response-Cost",
  tokensIn: "X-MapleAI-Tokens-In",
  tokensOut: "X-MapleAI-Tokens-Out",
  version: "X-MapleAI-Version",
} as const;
